### ISSUE TITLE
Doesn't work on Android 7

### ISSUE THREAD

**Issue by YtvwlD** [intika/XposedGmsCoreUnifiedNlp#2]
According to the [microG repository](https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation), Android devices >= 7 need [this patch](https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/patches/android_frameworks_base-N.patch) or UnifiedNlp does only work when put in `/system`.

Can this be included in this XPosed module?

**Comment by intika** [comment]
I will look into that on next version ;) 
i will post back when solved thank you for reporting back ;) this will be followed here [#3](https://github.com/Intika-Android-Apps/XposedGmsCoreUnifiedNlp/issues/3)
